
# @name Create Auth Credential
# @no-log

POST {{admin-app}}/auth-credential/create
Content-Type: application/json

{
  "type": "merchant",
  "userName": "easpos_mer",
  "password": "V5;>Ry(F^.B*$DNZ8,~#uj",
  "authServices": {
    "AuthCredentialService": [
      "GetAuthCredential"
    ]
  },
  "authPaths": []
}
