
# @name Create Auth Credential
# @no-log

POST {{admin-app}}/auth-credential/create
Content-Type: application/json

{
  "type": "admin_rpc",
  "userName": "easpos_adm_rpc",
  "password": "p</f=WxVwCEDX629ck3Z4&",
  "authServices": {
    "AuthCredentialService": [
      "GetAuthCredential"
    ],
    "MerchantService": [
      "TmpTst"
    ]
  }
}
