
# @name Create Auth Credential
# @no-log

POST {{admin-app}}/auth-credential/create
Content-Type: application/json

{
  "type": "admin_rpc",
  "userName": "easpos_adm",
  "password": "adm123",
  "allowedPeers": [
    "127.0.0.1:4002"
  ],
  "allowedServices": [
    {
      "service": "AuthCredential",
      "paths": [
        "create"
      ]
    }
  ]
}
