// @name Ms Test
// @no-log
GET {{user-app}}/ms-test?msg=ar bwr

###

// @name Create Merchant
// @no-log
POST {{user-app}}/create-merchant
Authorization: Basic easpos_usr V5;>Ry(F^.B*$DNZ8,~#uj
Content-Type: application/json

{
  "name": "EasPos",
  "mail": "tinkokowin@easpos.co",
  "phone": "09790000000",
  "verified": true
}
