// @name Ms Test
// @no-log
GET {{user-app}}/ms-test?msg=ar bwr

###

// @name Create Merchant
// @no-log

< {%
  request.variables.set('authorization', Window.btoa('easpos_mer:V5;>Ry(F^.B*$DNZ8,~#uj'))
%}

POST {{user-app}}/create-merchant
Authorization: Basic {{authorization}}
Content-Type: application/json

{
  "name": "EasPos",
  "mail": "tinkokowin@easpos.co",
  "mobileNo": "+959790000001",
  "category": {
    "name": "SAAS",
    "type": "Merchant"
  }
}
