export const PAGE_SIZE = 20;
export const ADMIN_URL = 'localhost:4001';

//Env
export const NODE_ENV = 'NODE_ENV';
export const ENV = 'ENV';
export const PRE_END_SUB_MAIL = 'PRE_END_SUB_MAIL';
export const MONGO_URI = 'MONGO_URI';
export const ENC_PASSWD = 'ENC_PASSWD';
export const COOKIE_SECRET = 'COOKIE_SECRET';
export const APP = 'APP';
export const SESSION_USER = 'SESSION_USER';
export const JWT_SECRET = 'JWT_SECRET';
export const REDIS_HOST = 'REDIS_HOST';
export const REDIS_PORT = 'REDIS_PORT';
export const REDIS_USR = 'REDIS_USR';
export const REDIS_PASSWORD = 'REDIS_PASSWORD';
export const REDIS_LCL_USR = 'REDIS_LCL_USR';
export const REDIS_LCL_PWD = 'REDIS_LCL_PWD';
export const USR_APP_USR = 'USR_APP_USR';
export const USR_APP_PWD = 'USR_APP_PWD';
export const ADM_MRO_USR = 'ADM_MRO_USR';
export const ADM_MRO_PWD = 'ADM_MRO_PWD';
export const TRT_TRS_LGT = 'TRT_TRS_LGT'; //NOTE: 6 hour
export const TRT_TRS_MDR = 'TRT_TRS_MDR'; //NOTE: 2 hour
export const TRT_TRS_HVY_F = 'TRT_TRS_HVY_F'; //NOTE: 1 minute
export const TRT_TRS_HVY_S = 'TRT_TRS_HVY_S'; //NOTE: 30 minute
export const TRT_TRS_HVY_T = 'TRT_TRS_HVY_T'; //NOTE: 3 hour
export const TRT_TRS_ITS = 'TRT_TRS_ITS'; // NOTE: 10 minute
